# Generated by Django 3.0.5 on 2020-04-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
