# Generated by Django 3.0.5 on 2020-04-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='res',
            field=models.IntegerField(default=0),
        ),
    ]
