# Generated by Django 3.0.5 on 2020-04-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200427_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sal',
            field=models.IntegerField(default=5000),
        ),
    ]
